#########################
# Garage Door           #
#########################
# When garage door opens, turn on light in kitchen...
# IF after sunset, and no other kitchen lights are on, and luminance is low
# (Only fires in the evening - not in the morning because we're probably leaving
# the house. This could be improved with presence detection?)
# * Includes luminance sensor; probably overkill with switches, but meh
- id: '1539744009480'
  alias: Indoor Light when Garage Door Opens
  trigger:
  - platform: state
    entity_id: cover.garage_door
    from: 'closed'
    to: 'open'
  condition:
    - condition: sun
      after: sunset
    - condition: state
      entity_id: light.kitchen_side_level
      state: 'off'
    - condition: state
      entity_id: light.kitchen_center_level
      state: 'off'
    - condition: state
      entity_id: light.kitchen_main_level
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.kitchen_multi_luminance
      below: 20
  action:
  - service: homeassistant.turn_on
    entity_id: light.kitchen_entry_level

# Turn on garage lights when door opens
# IF sun is down
- id: 'garagelightson'
  alias: Garage Door Lights On
  trigger:
  - platform: state
    entity_id: cover.garage_door
    from: 'closed'
    to: 'open'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.garage_light

# Turn off garage lights when door closes
# IF sun is down
- id: 'garagelightsoff'
  alias: Garage Door Lights Off
  trigger:
  - platform: state
    entity_id: cover.garage_door
    from: 'open'
    to: 'closed'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.garage_light


#########################
# Audio                 #
#########################
# Note: All of these have conditions attached to only turn off when already on, and
# vice-versa. This is because the Chromecasts are super flaky and often flip to
# "unavailable" randomly throughout the day, so this helps clean up the logs
# a tiny bit.

- id: 'radioampon'
  alias: Amp Auto-On - Radio
  trigger:
  - platform: state
    entity_id: media_player.radio
    to: 'playing'
  - platform: state
    entity_id: media_player.all_indoor
    to: 'playing'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'playing'
  - platform: state
    entity_id: media_player.main_floor
    to: 'playing'
  - platform: state
    entity_id: media_player.main_and_basement
    to: 'playing'
  condition:
    - condition: state
      entity_id: switch.radio_amp
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.radio_amp


- id: 'radioampoff'
  alias: Amp Auto-Off - Radio
  trigger:
  - platform: state
    entity_id: media_player.radio
    to: 'off'
  - platform: state
    entity_id: media_player.all_indoor
    to: 'off'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'off'
  - platform: state
    entity_id: media_player.main_floor
    to: 'off'
  - platform: state
    entity_id: media_player.main_and_basement
    to: 'off'
  condition:
    - condition: state
      entity_id: switch.radio_amp
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.radio_amp


- id: 'deckampon'
  alias: Amp Auto-On - Deck
  trigger:
  - platform: state
    entity_id: media_player.deck
    to: 'playing'
  - platform: state
    entity_id: media_player.all_outdoor
    to: 'playing'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'playing'
  condition:
    - condition: state
      entity_id: switch.deck_amp
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.deck_amp


- id: 'deckampoff'
  alias: Amp Auto-Off - Deck
  trigger:
  - platform: state
    entity_id: media_player.deck
    to: 'off'
  - platform: state
    entity_id: media_player.all_outdoor
    to: 'off'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'off'
  condition:
    - condition: state
      entity_id: switch.deck_amp
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.deck_amp

- id: 'garageampon'
  alias: Amp Auto-On - Garage
  trigger:
  - platform: state
    entity_id: media_player.garage
    to: 'playing'
  - platform: state
    entity_id: media_player.all_outdoor
    to: 'playing'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'playing'
  condition:
    - condition: state
      entity_id: switch.garage_amp
      state: 'off'
  action:
  - service: homeassistant.turn_on
    entity_id: switch.garage_amp


- id: 'garageampoff'
  alias: Amp Auto-Off - Garage
  trigger:
  - platform: state
    entity_id: media_player.garage
    to: 'off'
  - platform: state
    entity_id: media_player.all_outdoor
    to: 'off'
  - platform: state
    entity_id: media_player.all_indoor_and_outdoor
    to: 'off'
  condition:
    - condition: state
      entity_id: switch.garage_amp
      state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: switch.garage_amp


#########################
# Outdoor Lights        #
#########################
- id: 'alloutdooron'
  alias: Porch Switch - Double Tap All On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_outdoor_front_porch
      scene_id: 1
      scene_data: 7860
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.outdoor_front_porch_light
    - service: homeassistant.turn_on
      data:
        entity_id: switch.outdoor_front_house_light
    - service: homeassistant.turn_on
      data:
        entity_id: switch.outdoor_driveway_light
        
- id: 'alloutdooroff'
  alias: Porch Switch - Double Tap All Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_outdoor_front_porch
      scene_id: 2
      scene_data: 7860
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.outdoor_front_porch_light
    - service: homeassistant.turn_off
      data:
        entity_id: switch.outdoor_front_house_light
    - service: homeassistant.turn_off
      data:
        entity_id: switch.outdoor_driveway_light

#########################
# Basement Stair Light  #
#########################
- id: 'allbasementon'
  alias: Basement Switch - Triple Tap All Basement On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement_stair
      scene_id: 1
      scene_data: 7920
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.basement_stairs
    - service: homeassistant.turn_on
      data:
        entity_id: switch.basement_lights_south
    - service: homeassistant.turn_on
      data:
        entity_id: switch.basement_lights_north
        
- id: 'allbasementoff'
  alias: Basement Switch - Triple Tap All Basement Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement_stair
      scene_id: 2
      scene_data: 7920
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.basement_stairs
    - service: homeassistant.turn_off
      data:
        entity_id: switch.basement_lights_south
    - service: homeassistant.turn_off
      data:
        entity_id: switch.basement_lights_north

- id: 'allkitchenon'
  alias: Basement Switch - Double Tap All Kitchen On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement_stair
      scene_id: 1
      scene_data: 7860
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen_center_level
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen_main_level
    - service: homeassistant.turn_on
      data:
        entity_id: light.kitchen_side_level
        
- id: 'allkitchenoff'
  alias: Basement Switch - Double Tap All Kitchen Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.switch_basement_stair
      scene_id: 2
      scene_data: 7860
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.kitchen_center_level
    - service: homeassistant.turn_off
      data:
        entity_id: light.kitchen_main_level
    - service: homeassistant.turn_off
      data:
        entity_id: light.kitchen_side_level


#########################
# Bedroom               #
#########################
# Turn on bed heater if too cold
- id: 'bedheatermarkon'
  alias: Bed Heater Auto On - Mark
  trigger:
    - platform: time_pattern
      minutes: '/5'
      seconds: 00
  condition:
    - condition: time
      after: '23:00:00'
      before: '02:00:00'
    - condition: numeric_state
      entity_id: sensor.bedroom_multi_temperature
      below: 70
    - condition: state
      entity_id: switch.bedroom_bedwarmer_mark
      state: 'off'
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: switch.bedroom_bedwarmer_mark

# Turn off bed heater if too warm
- id: 'bedheatermarkoff'
  alias: Bed Heater Auto Off - Mark
  trigger:
    - platform: time_pattern
      minutes: '/6'
      seconds: 00
  condition:
    - condition: time
      after: '23:00:00'
      before: '02:00:00'
    - condition: numeric_state
      entity_id: sensor.bedroom_multi_temperature
      above: 70
    - condition: state
      entity_id: switch.bedroom_bedwarmer_mark
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.bedroom_bedwarmer_mark

# Always turn off bed heater in the middle of the night
- id: 'bedheatermarkofftime'
  alias: Bed Heater Auto Off - Mark
  trigger:
    - platform: time_pattern
      hours: 2
      minutes: 15
      seconds: 00
  condition:
    - condition: state
      entity_id: switch.bedroom_bedwarmer_mark
      state: 'on'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: switch.bedroom_bedwarmer_mark

# Turn on bedroom lamps with Hank controller
- id: 'bedroomlampson'
  alias: Bedroom Lamps - Turn On
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.button_bedroom_hank_four
      scene_id: 3
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.marks_light
    - service: homeassistant.turn_on
      data:
        entity_id: light.mollys_light

# Turn off bedroom lamps with Hank controller
- id: 'bedroomlampsoff'
  alias: Bedroom Lamps - Turn Off
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.button_bedroom_hank_four
      scene_id: 4
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.marks_light
    - service: homeassistant.turn_off
      data:
        entity_id: light.mollys_light

# Set lamp brightness to 75%
- id: 'bedroomlampsbrightup'
  alias: 'Make the lights go bright'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        scene_id: 2
        entity_id: zwave.button_bedroom_hank_four
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.marks_light
        brightness_pct: 75
    - service: homeassistant.turn_on
      data:
        entity_id: light.mollys_light
        brightness_pct: 75

# Set lamp brightness to 25%
- id: 'bedroomlampsbrightdown'
  alias: 'Make the lights go dim'
  trigger:
    - platform: event
      event_type: zwave.scene_activated
      event_data:
        scene_id: 1
        entity_id: zwave.button_bedroom_hank_four
  action:
    - service: homeassistant.turn_on
      data:
        entity_id: light.marks_light
        brightness_pct: 25
    - service: homeassistant.turn_on
      data:
        entity_id: light.mollys_light
        brightness_pct: 25


#########################
# Presence              #
#########################
- id: 'lightsoffondeparture'
  alias: Lights Off When Home Empty
  trigger:
    - platform: state
      entity_id: group.molly_and_mark
      from: 'home'
      to: 'not_home'
      for:
        minutes: 1
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_lights
    - service: homeassistant.turn_off
      data:
        entity_id: group.all_switches


#########################
# Button                #
#########################
- id: 'goodnightbutton'
  alias: Goodnight House Button
  trigger:
    platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.button_hank_one_scene
      scene_id: 1
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.goodnight


#########################
# Certificate           #
#########################
- id: letsencrypt-renewal
  alias: "Let's Encrypt Renewal"
  trigger:
  - platform: time
    at: '00:00:00'
  action:
  - service: hassio.addon_restart
    data:
      addon: core_letsencrypt