- id: '1592360741345'
  alias: Kitchen IKEA Remote Sleep
  description: ''
  trigger:
  - device_id: 4a780e30be2c4259b6f7417b317655c0
    domain: zha
    platform: device
    subtype: turn_on
    type: remote_button_short_press
  condition: []
  action:
  - data: {}
    entity_id: light.kitchen_center_level
    service: homeassistant.toggle
  mode: single
- id: '1597526054349'
  alias: Automatic Reboot
  description: ''
  trigger:
  - at: '3:30'
    platform: time
  condition: []
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
