#########################
# Basic Config
#########################
zwave:
  usb_path: /dev/ttyACM0

# Zigbee
#zha:
#  usb_path: /dev/ttyUSB0
#  database_path: /config/zigbee.db
  
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 860
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zoness
  time_zone: America/Detroit
  # Customization file
  customize: !include customize.yaml

# introduction:     # Show links to resources in log and frontend
# cloud:
config:             # Enables configuration UI
fastdotcom:         # Fast.com speed test
frontend:           # Enables the frontend
history:            # Enables support for tracking state changes over time
logbook:            # View all events in a logbook
map:                # Enables a map showing the location of tracked devices
person:             # Persons
system_health:      # System health stuff
updater:            # Checks for available updates
wake_on_lan:        # enables `wake_on_lan` domain

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml


http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  

# Discover some devices automatically
discovery:
  enable:
    - homekit


#########################
# Weather
#########################
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

#########################
# Sensors
#########################
sensor: !include sensors.yaml

binary_sensor:
  - platform: template
    sensors:
      bedroom_motion:
        friendly_name: 'Bedroom Motion'
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.bedroom_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      kitchen_motion:
        friendly_name: 'Kitchen Motion'
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.kitchen_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_mark:
        friendly_name: 'In Bed - Mark'
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_mark', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_molly:
        friendly_name: 'In Bed - Molly'
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_molly', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}

          

#########################
# Text to speech
#########################
tts:
  - platform: google

#########################
# Arlo Cameras
#########################
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

#########################
# Configurator
#########################
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_url

  vscode:
    title: Visual Studio Code
    icon: mdi:visual-studio-code
    url: !secret vscode_url

#########################
# Garage Door
#########################
cover:
  - platform: gogogate2
    username: !secret garagedoor_username
    password: !secret garagedoor_password
    ip_address: !secret garagedoor_ip

#########################
# Media
#########################
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret

# TV
  - platform: webostv
    name: Living Room TV
    host: !secret ip_tv

media_extractor:

#########################
# Notifications
#########################
notify:
  - platform: webostv
    host: !secret ip_tv
    name: livingroom_tv

  - platform: html5
    name: notify
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
    

#########################
# Google Assistant
#########################
# Hiding groups that come from Hue. Someday might swap this out to set up rooms
# here, rather than duplicating effort in GA. And/or use only groups from Hue
# and not exposing individual bulbs in GA. TBD.
cloud:
  google_actions:
    filter:
      include_domains:
        - switch
        - light
        - scene
      exclude_entities:
        - light.dining_room
        - light.living_room
        - light.main_floor_accents
        - light.bedroom

# google_assistant:
#   project_id: !secret google_assistant_projectid
#   api_key: !secret google_assistant_api
#   exposed_domains:
#     - switch
#     - light
#     - scene
#   entity_config:
#     light.custom_group_for_lights:
#       expose: false
#     light.custom_group_for_lights_2:
#       expose: false
#     light.dining_room:
#       expose: false
#     light.living_room:
#       expose: false
#     light.main_floor_accents:
#       expose: false
#     light.bedroom:
#       expose: false

# Google Home integration
# googlehome:
#   devices:
#     - host: !secret ip-googlehomehub
#       track_devices: false
#       track_alarms: true
#     - host: !secret ip-googlehome
#       track_devices: false
#       track_alarms: true
#     - host: !secret ip-googlehomemini-bedroom
#       track_devices: false
#       track_alarms: true
#     - host: !secret ip-googlehomemini-basement
#       track_devices: false
#       track_alarms: true
#     - host: !secret ip-googlehomemini-garage
#       track_devices: false
#       track_alarms: true


#########################
# Presence Detection
#########################

owntracks:
    waypoints: false # disable owntracks from reporting regions - prevents overlapping homes

device_tracker:
  - platform: automatic
    client_id: !secret automatic_id
    secret: !secret automatic_secret
    current_location: true
  - platform: netgear
    password: !secret router_password

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 90
    icon: mdi:home
  - name: WFS
    latitude: !secret wfs_latitude
    longitude: !secret wfs_longitude
    radius: 90
    icon: mdi:worker
  - name: A-O
    latitude: !secret ao_latitude
    longitude: !secret ao_longitude
    radius: 540
    icon: mdi:worker

#########################
# Radio Player Config
#########################
input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - BBC Radio 1
      - BBC Radio 1 Xtra
      - WIOG 102.5
      - RTE 2FM
      - Hotmix Japan
      - The Bounce 105.1
      - NRJ Sweden
      - Amp Radio Calgary
      - Groove Salad
      - Deep House Lounge

  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Kitchen
      - Living Room
      - Main Floor
      - Main and Basement
      - Bedroom
      - All Indoor
      - Garage
      - Deck
      - Everywhere
    initial: Kitchen
    icon: mdi:speaker-wireless
