#########################
# Basic Config
#########################
zwave:
  usb_path: /dev/ttyACM0

# Zigbee
#zha:
#  usb_path: /dev/ttyUSB0
#  database_path: /config/zigbee.db
  
homeassistant:
  # Customization file
  customize: !include customize.yaml

# introduction:     # Show links to resources in log and frontend
cloud:
default_config:     # default config
fastdotcom:         # Fast.com speed test
wake_on_lan:        # enables `wake_on_lan` domain
zeroconf:
discovery:          # Discover some devices automatically
  ignore:
    - apple_tv

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:
  themes: !include themes.yaml

http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: !secret base_url
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
  
#########################
# Google
#########################
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

#########################
# Weather
#########################
sun:

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api
    mode: freedaily
  - platform: nws
    api_key: !secret nws_api
    station: KLAN
    mode: daynight
#  - platform: darksky
#    api_key: !secret darksky_api
#    mode: daily

#########################
# Sensors
#########################
sensor: !include sensors.yaml

binary_sensor:
  - platform: template
    sensors:
      bedroom_motion:
        friendly_name: 'Bedroom Motion'
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.bedroom_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      kitchen_motion:
        friendly_name: 'Kitchen Motion'
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.kitchen_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_mark:
        friendly_name: 'In Bed - Mark'
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_mark', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_molly:
        friendly_name: 'In Bed - Molly'
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_molly', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}

#########################
# Custom Panel
#########################
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

#########################
# HACS
#########################
hacs:
  token: !secret hacs_github_token
  theme: true

#########################
# Pi Hole
#########################
pi_hole:
  host: !secret pihole_host

#########################
# Text to speech
#########################
tts:
  - platform: google_translate
    service_name: google_say

#########################
# Arlo Cameras
#########################
arlo:
  username: !secret arlo_username
  password: !secret arlo_password

#########################
# Garage Door
#########################
cover:
  - platform: gogogate2
    username: !secret garagedoor_username
    password: !secret garagedoor_password
    ip_address: !secret garagedoor_ip

#########################
# Media
#########################
media_player:
  - platform: spotify
    client_id: !secret spotify_id
    client_secret: !secret spotify_secret

# TV
  - platform: webostv
    name: Living Room TV
    host: !secret ip_tv

media_extractor:

#########################
# Notifications
#########################
notify:
  - name: livingroom_tv
    platform: webostv
    host: !secret ip_tv

  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email
    
  - name: molly_and_mark
    platform: group
    services:
      - service: html5_pixel3
      - service: mobile_app_markd_mobile_app

  - name: mark
    platform: group
    services:
      - service: html5_pixel3
      - service: mobile_app_markd_mobile_app

#########################
# Presence Detection
#########################

owntracks:
    waypoints: false # disable owntracks from reporting regions - prevents overlapping homes

device_tracker:
  - platform: automatic
    client_id: !secret automatic_id
    secret: !secret automatic_secret
    current_location: true
  - platform: netgear
    password: !secret router_password
#    accesspoints: true
    accesspoints:
      - !secret router_orbi_mac
      - !secret upstairs_orbi_mac
      - !secret garage_orbi_mac
    devices:
      - !secret molly_mobile_mac
      - !secret markd_mobile_mac

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 90
    icon: mdi:home
  - name: WFS
    latitude: !secret wfs_latitude
    longitude: !secret wfs_longitude
    radius: 90
    icon: mdi:worker
  - name: A-O
    latitude: !secret ao_latitude
    longitude: !secret ao_longitude
    radius: 540
    icon: mdi:worker

#########################
# Spotcast
#########################
spotcast:
  username: !secret spotify_username
  password: !secret spotify_password


#########################
# Radio Player Config
#########################
input_select:
  radio_station:
    name: 'Select Radio Station:'
    options:
      - BBC Radio 1
      - BBC Radio 1 Xtra
      - WIOG 102.5
      - RTE 2FM
      - Hotmix Japan
      - The Bounce 105.1
      - NRJ Sweden
      - Amp Radio Calgary
      - Groove Salad
      - Deep House Lounge

  chromecast_radio:
    name: 'Select Speakers:'
    options:
      - Kitchen
      - Living Room
      - Main Floor
      - Main and Basement
      - Bedroom
      - All Indoor
      - Garage
      - Deck
      - Everywhere
    initial: Kitchen
    icon: mdi:speaker-wireless

  spotify_playlist:
    name: 'Select Playlist:'
    options:
      - Discover Weekly
      - Release Radar
      - Bangin Christmas Party
      - Bangin Dinner Party
      - CRJ Radio
      - Sunset Mix
      - Chillout Mix
      - Beats Mix

#########################
# Logging
#########################
recorder:
  purge_keep_days: 8
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.disk_use_percent
      - sensor.processor_use
      - sensor.rbr50_gateway_bytes_received
      - sensor.rbr50_gateway_bytes_sent
      - sensor.rbr50_gateway_kbyte_sec_received
      - sensor.rbr50_gateway_kbyte_sec_sent
      - sensor.rbr50_gateway_packets_received
      - sensor.rbr50_gateway_packets_sec_received
      - sensor.rbr50_gateway_packets_sec_sent
      - sensor.rbr50_gateway_packets_sent
    domains:
      - updater
      - zone
      - zwave
