#########################
# Basic Config
#########################
zwave:
  usb_path: /dev/ttyACM0
  config_path: /config/ozw_config/openzwave/config/
  device_config:
    light.nursery_fan_level:
      refresh_value: true
      polling_intensity: 1
    light.nursery_light_level:
      refresh_value: true
      polling_intensity: 1

# Zigbee
zha:
  zigpy_config:
    ota:
      ikea_provider: true # Auto update Trådfri devices

zha_map:

homeassistant:
  # Customization file
  customize: !include customize.yaml

logger:
  default: info
  logs:
    homeassistant.components.zha: notset
#    homeassistant.components.zha: debug
#    zigpy: debug

# introduction:     # Show links to resources in log and frontend
cloud:
default_config: # default config
fastdotcom: # Fast.com speed test
wake_on_lan: # enables `wake_on_lan` domain
zeroconf:
discovery: # Discover some devices automatically
  ignore:
    - apple_tv

# Includes
group: !include groups.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automations
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml

frontend:
  themes: !include_dir_merge_named themes

http:
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem

#########################
# Google
#########################
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

google_domains:
  domain: !secret google_ddns_domain
  username: !secret google_ddns_id
  password: !secret google_ddns_pw

#########################
# Weather
#########################
sun:

weather:
  - platform: darksky
    api_key: !secret darksky_api
    mode: daily

#########################
# Sensors
#########################
sensor: !include sensors.yaml

binary_sensor:
  - platform: template
    sensors:
      bedroom_motion:
        friendly_name: "Bedroom Motion"
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.bedroom_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      kitchen_motion:
        friendly_name: "Kitchen Motion"
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.kitchen_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      garage_motion:
        friendly_name: "Garage Motion"
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.garage_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      office_motion:
        friendly_name: "Office Motion"
        device_class: motion
        value_template: >-
          {%- if is_state('sensor.office_multi_burglar', '0') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_mark:
        friendly_name: "In Bed - Mark"
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_mark', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}
      bed_molly:
        friendly_name: "In Bed - Molly"
        device_class: presence
        value_template: >-
          {%- if is_state('binary_sensor.bedroom_bed_molly', 'on') -%}
          false
          {%- else -%}
          true
          {%- endif -%}

#########################
# Fan
#########################
fan:
  - platform: template
    fans:
      nursery_fan:
        friendly_name: "Nursery Fan"
        value_template: "{{ states('light.nursery_fan_level') }}"
        speed_template: >
          {% set output = {0: 'off', 85: 'low', 170: 'medium', 255: 'high'} %}
          {% set idx = state_attr('light.nursery_fan_level', 'brightness') %}
          {{ output[idx] }}
        turn_on:
          service: light.turn_on
          entity_id: light.nursery_fan_level
        turn_off:
          service: light.turn_off
          entity_id: light.nursery_fan_level
        set_speed:
          service: light.turn_on
          entity_id: light.nursery_fan_level
          data_template:
            brightness: >
              {% set mapper = {'off' : 0, 'low': 85, 'medium': 170, 'high': 255} %}
              {{ mapper[speed] }}
        speeds:
          - "off"
          - "low"
          - "medium"
          - "high"

#########################
# Custom Panel
#########################
panel_custom:
  - name: zwave-graph-panel
    url_path: zwave-graph
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:z-wave
    module_url: /local/zwavegraph3.js
    config:
      # ranker - pick one: network-simplex, tight-tree, longest-path
      ranker: network-simplex
      # edge_visibility - pick one: relevant, all
      edge_visibility: relevant
      # grouping - pick one: z-wave, ungrouped
      grouping: z-wave

#########################
# Text to speech
#########################
tts:
  - platform: google_translate
    service_name: google_say

#########################
#  Cameras
#########################
#arlo:
#  username: !secret arlo_username
#  password: !secret arlo_password

#########################
# Media
#########################
media_player:

spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

media_extractor:

#########################
# Notifications
#########################
notify:
  - name: html5
    platform: html5
    vapid_pub_key: !secret vapid_pub_key
    vapid_prv_key: !secret vapid_prv_key
    vapid_email: !secret vapid_email

  - name: molly_and_mark
    platform: group
    services:
      - service: mobile_app_pixel_3
      - service: mobile_app_molly_dehate

  - name: mark
    platform: group
    services:
      - service: mobile_app_pixel_3

#########################
# Presence Detection
#########################

owntracks:
  waypoints: false # disable owntracks from reporting regions - prevents overlapping homes

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 90
    icon: mdi:home
  - name: WFS
    latitude: !secret wfs_latitude
    longitude: !secret wfs_longitude
    radius: 90
    icon: mdi:account-hard-hat
  - name: A-O
    latitude: !secret ao_latitude
    longitude: !secret ao_longitude
    radius: 540
    icon: mdi:account-hard-hat

#########################
# Spotcast
#########################
spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

#########################
# Camera
#########################
camera:
  - platform: foscam
    ip: !secret foscam_ip
    rtsp_port: !secret foscam_rtsp_port
    username: !secret foscam_username
    password: !secret foscam_password
  - platform: generic
    name: WyzeCam
    still_image_url: "null"
    stream_source: !secret wyzecam_addy

#########################
# Radio Player Config
#########################
# Adding an audio destination? Add it to these places:
# input_select - chromecast_radio_value
# input_select - chromecast_radio
# automation - sync_radio_input_selects

input_select:
  chromecast_radio_value:
    name: "Selected Speaker:"
    options:
      - media_player.kitchen
      - media_player.radio
      - media_player.main_floor
      - media_player.main_and_basement
      - media_player.bedroom
      - media_player.basement
      - media_player.all_indoor
      - media_player.garage
      - media_player.deck
      - media_player.all_indoor_and_outdoor
    initial: media_player.kitchen

  chromecast_radio:
    name: "Select Speakers:"
    options:
      - Kitchen
      - Living Room
      - Main Floor
      - Main and Basement
      - Basement
      - Bedroom
      - All Indoor
      - Garage
      - Deck
      - Everywhere
    initial: Kitchen
    icon: mdi:speaker-wireless

  spotify_playlist:
    name: "Select Playlist:"
    options:
      - Discover Weekly
      - Release Radar
      - Bangin Christmas Party
      - Bangin Dinner Party
      - CRJ Radio
      - Sunset Mix
      - Chillout Mix
      - Beats Mix

#########################
# Logging
#########################
recorder:
  purge_keep_days: 8
  exclude:
    entities:
      - sensor.date
      - sensor.date_time
      - sensor.date_time_iso
      - sensor.time_date
      - sensor.internet_time
      - sensor.time_utc
      - sensor.time
      - sensor.time_12hr
      - sensor.memory_free
      - sensor.memory_use_percent
      - sensor.disk_use_percent
      - sensor.processor_use
      - sensor.rbr50_gateway_bytes_received
      - sensor.rbr50_gateway_bytes_sent
      - sensor.rbr50_gateway_kbyte_sec_received
      - sensor.rbr50_gateway_kbyte_sec_sent
      - sensor.rbr50_gateway_packets_received
      - sensor.rbr50_gateway_packets_sec_received
      - sensor.rbr50_gateway_packets_sec_sent
      - sensor.rbr50_gateway_packets_sent
    domains:
      - updater
      - zone
      - zwave
