- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - temperature
    - humidity
    - temperature_high
  scan_interval:
    minutes: 5

- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - humidity

- platform: template
  sensors:
    kitchen_multi_battery:
      value_template: "{{ states.zwave.sensor_kitchen_multi.attributes.battery_level }}"
      friendly_name: "Kitchen Multi Sensor Battery"
      entity_id: zwave.sensor_kitchen_multi
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level_xod1 = states.zwave.sensor_kitchen_multi.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('zwave.sensor_kitchen_multi', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
    bedroom_multi_battery:
      value_template: "{{ states.zwave.sensor_bedroom_multi.attributes.battery_level }}"
      friendly_name: "Bedroom Multi Sensor Battery"
      entity_id: zwave.sensor_bedroom_multi
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level_xod1 = states.zwave.sensor_bedroom_multi.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('zwave.sensor_bedroom_multi', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
    garage_multi_battery:
      value_template: "{{ states.zwave.sensor_garage_multi.attributes.battery_level }}"
      friendly_name: "Garage Multi Sensor Battery"
      entity_id: zwave.sensor_garage_multi
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level_xod1 = states.zwave.sensor_garage_multi.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('zwave.sensor_garage_multi', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
    hank_four_button_battery:
      value_template: "{{ states.zwave.button_bedroom_hank_four.attributes.battery_level }}"
      friendly_name: "Bedroom Four Button Battery"
      entity_id: zwave.button_bedroom_hank_four
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level_xod1 = states.zwave.button_bedroom_hank_four.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('zwave.button_bedroom_hank_four', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}
    hank_one_button_battery:
      value_template: "{{ states.zwave.button_hank_one_scene.attributes.battery_level }}"
      friendly_name: "Hank One Button Battery"
      entity_id: zwave.button_hank_one_scene
      unit_of_measurement: '%'
      icon_template: >
        {% set battery_level_xod1 = states.zwave.button_hank_one_scene.attributes.battery_level|default(0)|int %}
        {% set battery_round_xod1 = (battery_level_xod1 / 10) |int * 10 %}
        {% if battery_round_xod1 >= 100 or is_state('zwave.button_hank_one_scene', 'unknown') %}
          mdi:battery
        {% elif battery_round_xod1 > 0 %}
          mdi:battery-{{ battery_round_xod1 }}
        {% else %}
          mdi:battery-charging-wireless-outline
        {% endif %}

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'