- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - temperature
    - humidity
    - temperature_high
  scan_interval:
    minutes: 5

- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - humidity

- platform: template
  sensors:
    kitchen_multi_battery:
      value_template: "{{ states.zwave.sensor_kitchen_multi.attributes.battery_level }}"
      friendly_name: "Kitchen Multi Sensor Battery"
      entity_id: zwave.sensor_kitchen_multi
      unit_of_measurement: '%'
    bedroom_multi_battery:
      value_template: "{{ states.zwave.sensor_bedroom_multi.attributes.battery_level }}"
      friendly_name: "Bedroom Multi Sensor Battery"
      entity_id: zwave.sensor_bedroom_multi
      unit_of_measurement: '%'
    garage_multi_battery:
      value_template: "{{ states.zwave.sensor_garage_multi.attributes.battery_level }}"
      friendly_name: "Garage Multi Sensor Battery"
      entity_id: zwave.sensor_garage_multi
      unit_of_measurement: '%'
    time_12hr:
      value_template: "{{ as_timestamp(states('sensor.date_time_iso')) | timestamp_custom('%-I:%M') }}"

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: memory_use_percent
    - type: processor_use

- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'